alias nb='jupyter notebook'
alias gs='git status'
alias gt='git log --graph --oneline --decorate --all -n 20'
alias go='xdg-open'
alias k='kubectl'
alias pjson='python -m json.tool'
alias tldr='docker run --rm -it -v ~/.tldr/:/root/.tldr/ nutellinoit/tldr'
